"""Alert model — stores fraud alerts generated by SAGRA."""

from datetime import datetime, timezone
from sqlalchemy import String, Float, DateTime, Text
from sqlalchemy.orm import Mapped, mapped_column
from app.database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(String(50), primary_key=True)
    tx_id: Mapped[str] = mapped_column(String(50), index=True)
    type: Mapped[str] = mapped_column(String(50))  # e.g. "fraud_detected", "high_risk_cluster"
    severity: Mapped[str] = mapped_column(String(10))  # critical, high, medium
    status: Mapped[str] = mapped_column(String(20), default="active")  # active, resolved, dismissed
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    sender: Mapped[str] = mapped_column(String(20), default="")
    receiver: Mapped[str] = mapped_column(String(20), default="")
    amount: Mapped[float] = mapped_column(Float, default=0.0)
    risk_score: Mapped[float] = mapped_column(Float, default=0.0)
    trigger_reason: Mapped[str] = mapped_column(Text, default="")

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "tx_id": self.tx_id,
            "type": self.type,
            "severity": self.severity,
            "status": self.status,
            "timestamp": self.timestamp.isoformat() + "Z",
            "sender": self.sender,
            "receiver": self.receiver,
            "amount": self.amount,
            "risk_score": round(self.risk_score, 4),
            "trigger_reason": self.trigger_reason,
        }
